POST /connectors HTTP/1.1
Host: connect:8083
Content-Type: application/json
Accept: application/json

{
    "name":"sink",
    "config": {
        "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
        "connection.url": "jdbc:postgresql://database:5432/project3",
        "connection.user": "postgres",
        "connection.password": "nopass",
        "dialect.name": "PostgreSqlDatabaseDialect",
        "poll.interval.ms" : "60000",
        "topics.regex": "resultsEx",
        "insert.mode": "insert",
        "auto.create": true,
        "table.name.format": "auto_${topic}"
    }
    
}

#Para verificar a tabela do sink, em vez de usar o nome normalmente, usar "<nome_db>" 

###
GET /connectors HTTP/1.1
Host: connect:8083

###
DELETE /connectors/sink HTTP/1.1
Host: connect:8083

###
{"schema":{"type":"struct","fields":[{"type":"string","optional":false,"field":"result"}],"optional":false},"payload":{"result":"27"}}

{"schema":{"type":"struct","fields":[{"type":"string","optional":false,"field":"result"}],"optional":false,"name":"total data"},"payload":{"result":"27"}}